### PR TITLE
don't publish to test pypi

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Review by altendky — APPROVED** [review]
I hate to see these go, but since we haven't fixed the issues around them...

**Comment by altendky** [comment]
Though this could just go to `main` directly?

**Comment by arvidn** [comment]
my main motivation for this is to get https://github.com/Chia-Network/clvm_tools/pull/95 green

**Comment by altendky** [comment]
Mm, also, the granular path would have avoided dismissing the approving review on #95 and we wouldn't have waited for Adam to decide they want this in their branch.  `:]`

**Pull request merged**
